### ISSUE TITLE
NEOLINK close automatically- low FPS

### ISSUE THREAD

**Issue by MicheleCardamone** [QuantumEntangledAndy/neolink#150]
As you requested I open a new thread. Problem 1: neolink seems to have closed on its own after several hours of operation. I put it back to testing to avoid any other problems. Problem 2: As in the photo attached above, there appear to be totally dropped frames

**Comment by QuantumEntangledAndy** [comment]
For 1. should probably turn on debug logs set the `RUST_LOG` environemental variable to `debug`

For 2. If you are expecting to never drop frames.... I can't help you there. Unless there is some part of the code that I can point to to fix something then I can't address it. In 90% of the cases of dropped frames that I have seen the camera is just not sending them fast enough or the network is too congested. You could try running multiple instances of neolink with only a few cameras each since you have soo many cameras

**Comment by QuantumEntangledAndy** [comment]
You need to change the port for the rtsp. Only one app can use a port at a time. It can be changed in the config

**Comment by QuantumEntangledAndy** [comment]
Closing this since no actionable code changes can be made
