### ISSUE TITLE
Document the Binary XML protocol & Update wireshark dissector.

### ISSUE THREAD

**Issue by byteit101** [QuantumEntangledAndy/neolink#280]
**Is your feature request related to a problem? Please describe.**
It looks like newer firmware versions use a binary representation of the XML. It would be nice to decode this and add it to the wireshark dissector

**Describe the solution you'd like**
It would be great to document all the XML endpoints now so that they can be used in the reverse engineering of the binary format. I've created wireshark dissectors before, and love doing protocol decoding, so I don't mind doing some of the grunt work. However, I'm busy for the next 4-6ish months, so if someone can ensure the [messages](https://github.com/QuantumEntangledAndy/neolink/blob/master/dissector/messages.md) and other institutional knowledge is fully documented I, or anyone who does this before I get to it, would be able to decode the binary much quicker, hopefully. 

I have already determined that it isn't encrypted for `<Ip>` packets, as I found my mac address and IP address at byte 7 and 26, respectively

**Comment by QuantumEntangledAndy** [comment]
Could you send a packet capture that is in this binary format? Would be nice to see what you mean

**Comment by byteit101** [comment]
I'm actually not sure if this is "newer" or legacy. I couldn't get the new Reolink client 8.15 running on wine, so used the older 8.8.5. 

This capture has me looking at most settings in two cameras, sequentially. Both are on their respective latest firmware. I included all traffic attributable to the cameras, and I temporarily set the password to `Password1` before capturing.

[TwoCameras.pcapng.gz](https://github.com/user-attachments/files/16134775/TwoCameras.pcapng.gz)

**Comment by QuantumEntangledAndy** [comment]
The packets you sent are normal and not binary, they are encrypted with the usual AES encryption that we see with these cameras.

There is an additional complication with the decryptor because of the way you are looking at two cameras at once. For successful decryption it requires a) the password and b) the NONCE. The NONCE is shared during login and is different on each connection. Currently the dissector uses the most recently seen NONCE (that way it is correct over multiple reconnect in the same capture). However, since you have two cameras the NONCE will be the last camera that logged in (206 in the capture you sent). If you use wireshark to split the capture into two files based on IP then everything works and is decryptable

**Comment by QuantumEntangledAndy** [comment]
Perhaps the way to address the dissector changes would be to create a table of NONCE based on the IP pair

**Comment by QuantumEntangledAndy** [comment]
I pushed a quick dissector update that should handle the case of multiple cameras using AES

**Comment by QuantumEntangledAndy** [comment]
I'll close this since I think it is all addressed now but feel free to add more if you want
